#pragma config(Sensor, in1,    armSensor,      sensorPotentiometer)
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		clearLCDLine(0);
		displayLCDNumber(0, 0, SensorValue[armSensor]);
		wait1Msec(100);
	}
}
