#pragma config(Motor,  port1,           rampLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rampRight,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define JOYSTICK_DEADZONE 10
enum JoystickChannel { //define constants to make joystick usage easier to understand
	RX = 0,
	RY = 1,
	LY = 2,
	LX = 3
};

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

void pre_auton() {}

task autonomous() {}

task usercontrol() {
	int joystickY, joystickS;
	int leftPower, rightPower;
	while (true) {
		joystickY = vexRT[LY];
		if (abs(joystickY) < JOYSTICK_DEADZONE) joystickY = 0;
		joystickS = vexRT[RX];
		if (abs(joystickS) < JOYSTICK_DEADZONE) joystickS = 0;
		if (vexRT[Btn6U]) {
			joystickY /= 2;
			joystickS /= 2;
		}
		leftPower  = ( joystickY + joystickS) / 2;
		rightPower = (-joystickY + joystickS) / 2;
		motor[left] = leftPower;
		motor[right] = rightPower;
		if (vexRT[Btn5D]) {
			motor[rampLeft] = 100;
			motor[rampRight] = -100;
		}
		else {
			motor[rampRight] = 0;
			motor[rampLeft] = 0;
		}
		wait1Msec(10);
	}
}
