#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           arm,           tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define JOYSTICK_DEADZONE 10
enum JoystickChannel { //define constants to make joystick usage easier to understand
	RX = 0,
	RY = 1,
	LY = 2,
	LX = 3
};

#define ARM_UP_POWER 127
#define ARM_DOWN_POWER -127

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

void drive(int y, int s) {
	int leftPower  = -y + s;
	int rightPower = +y + s;
	int maxPower = abs(leftPower);
	if (abs(rightPower) > maxPower) maxPower = abs(rightPower);
	if (maxPower > 127) {
		leftPower = leftPower * 127 / maxPower;
		rightPower = rightPower * 127 / maxPower;
	}
	motor[left] = leftPower;
	motor[right] = rightPower;
}

void pre_auton() {}

task autonomous() {
	clearTimer(T1);
	while (time1[T1] < 1800) {
		drive(time1[T1] / 5, 0);
		wait1Msec(10);
	}
	drive(0, 0);
	motor[arm] = ARM_DOWN_POWER;
	wait1Msec(2000);
	motor[arm] = 0;
}

task usercontrol() {
	while (true) {
		int joystickY = vexRT[LY];
		if (abs(joystickY) < JOYSTICK_DEADZONE) joystickY = 0;
		int joystickS = vexRT[RX];
		if (abs(joystickS) < JOYSTICK_DEADZONE) joystickS = 0;
		if (vexRT[Btn6U]) {
			joystickY /= 2;
			joystickS /= 2;
		}
		drive(joystickY, joystickS);
		int armPower;
		if (vexRT[Btn5U]) armPower = ARM_UP_POWER;
		else if (vexRT[Btn5D]) armPower = ARM_DOWN_POWER;
		else armPower = 0;
		motor[arm] = armPower;
		wait1Msec(10);
	}
}
