#pragma config(Sensor, in1,    armSensor,      sensorPotentiometer)
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	sbyte yj, sj; //forward and spin movement variables
	sbyte aj, cj; //arm and claw movement variables
	bool lastBtn6D = false; //whether or not the right lower button was pressed the last loop cycle
	bool closed = false; //whether the claw should be closed
	while (true) { //infinite loop
		if (abs(vexRT[2]) > 10) yj = vexRT[2]; //if moving the joystick a significant amount, set the desired movement
		else yj = 0; //otherwise, set the movement to 0
		if (abs(vexRT[3]) > 10) sj = vexRT[3];
		else sj = 0;

		if (abs(vexRT[1]) > 10) aj = vexRT[1];
		else aj = 10; //to make the arm fall slower

		if (vexRT[Btn6D] && !lastBtn6D) { //if pressing the right lower button after it has been unpressed
			closed = !closed; //toggle the state of the claw
			lastBtn6D = true; //to prevent toggling multiple times
			clearTimer(T1); //to time the closing of the claw
		}
		if (!vexRT[Btn6D]) lastBtn6D = false; //if no longer pressing the button, allow it to be toggled again
		if (time1[T1] < 500) { //if in the first 500 milliseconds after closing
			if (closed) cj = 64; //if trying to close the claw, close it
			else cj = -64; //if trying to open the claw, open it
		}
		else cj = 0; //if claw has not recently been toggled, don't move it

		//APPLY MOTOR POWERS
		motor[left] =   yj + sj;
		motor[right] = -yj + sj;
		motor[arm] = -aj;
		motor[claw] = cj;

		wait1Msec(10); //allow other tasks to run
	}
}
